version: '3'

tasks:
  check:
    desc: Run lint and format checks
    cmds:
      - uv run ruff check src --fix
      - uv run ruff format src

  run:
    desc: Run Outfit Retargeting
    cmds:
      - |
        PYTHONPATH=src blender --background --python -m main -- \
          --base base.blend \
          --base-fbx avatar.fbx \
          --config config.json \
          --init-pose init_pose.json \
          --output output.fbx
