version: '3'

tasks:
  sync:
    desc: Install dependencies
    cmds:
      - uv sync

  check:
    desc: Run lint and format checks
    cmds:
      - uv run ruff check src
      - uv run ruff format src

  compile:
    desc: Alias for check
    cmds:
      - task: check

  run:

    desc: Run Outfit Retargeting
    cmds:
      - |
        PYTHONPATH=src blender --background --python -m main -- \
          --base base.blend \
          --base-fbx avatar.fbx \
          --config config.json \
          --init-pose init_pose.json \
          --output output.fbx
